services:
  # npm: 
  #   build: 
  #     context: .
  #     dockerfile: dockerfiles/npm.dockerfile
  #   volumes:
  #     - "./:/app"
  #   stdin_open: true
  #   tty: true
  server-1:
    build:
      context: .
      dockerfile: dockerfiles/server.dockerfile
    ports:
      - 1111:3000
    volumes:
      - "./:/app"
  server-2:
    build:
      context: .
      dockerfile: dockerfiles/server.dockerfile
    ports:
      - 2222:3000
    volumes:
      - "./:/app"
  server-3:
    build:
      context: .
      dockerfile: dockerfiles/server.dockerfile
    ports:
      - 3333:3000
    volumes:
      - "./:/app"
  server-4:
    build:
      context: .
      dockerfile: dockerfiles/server.dockerfile
    ports:
      - 4444:3000
    volumes:
      - "./:/app"
